make assert class partial
microsoft/testfx pull request #1238
Opened 2022-09-09 15:19 UTC by engyebrahim

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.cs
> +        return string.Compare(expected, actual, ignoreCase ,culture);
Please revert this change.

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.cs
>      #endregion
You can remove this region and the helper region.

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.AreEqual.cs
> +
Nit: Un-needed blank line.

```suggestion
```

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.Boolean.cs
> +
Nit: Un-needed blank line.

```suggestion
```

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.Boolean.cs
> +public sealed partial class Assert
We should probably follow the pattern used for other files (i.e. rename this file as `Assert.IsTrue`).

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.EqualsAssertion.cs
> +
Nit: un-needed blank line

```suggestion
```

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.EqualsAssertion.cs
> +    public static new bool Equals(object objA, object objB)
I would keep this method in the `Assert.cs` file. This is just to ensure people are not using equality.

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.Null.cs
> +public sealed partial class Assert
File should be named `Assert.IsNull` to follow the pattern of other files.

2022-09-09 15:38 UTC, Evangelink commented on src/TestFramework/MSTest.Core/Assertions/Assert.Type.cs
> +public sealed partial class Assert
File should be named `Assert.IsInstanceOfType` to follow the other files.

2022-09-09 16:17 UTC, Evangelink requested changes
Let's not add the new overloads in this PR.

2022-09-09 23:56 UTC, Haplois requested changes

2022-09-09 23:56 UTC, Haplois commented on src/TestFramework/MSTest.Core/Assertions/Assert.IsNull .cs
> +// Copyright (c) Microsoft Corporation. All rights reserved.
Remove the space just before the extension from the file name.

2022-09-12 07:30 UTC, Evangelink reviewed
One last round of changes and we are good to go! Thanks @engyebrahim

2022-09-12 07:30 UTC, Evangelink commented on test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.AreEqualTests.cs
> +    #region AreNotEqual tests.
You can remove the region.

2022-09-12 11:23 UTC, Evangelink approved these changes

2022-09-12 11:29 UTC, merged