Generate Correlation ID between hosts
microsoft/testfx pull request #3670
Opened 2024-08-22 12:14 UTC by mariam-abdulla

2024-08-22 12:17 UTC, Evangelink commented on src/Platform/Microsoft.Testing.Platform/DotnetTest/DotnetTestConnection.cs
> +    public DotnetTestConnection(CommandLineHandler commandLineHandler, ITestApplicationModuleInfo testApplicationModuleInfo, CTRLPlusCCancellationTokenSource cancellationTokenSource)
I would suggest to use the interface instead of the implementation class for the token source.

2024-08-22 12:17 UTC, Evangelink commented on src/Platform/Microsoft.Testing.Platform/DotnetTest/DotnetTestHelper.cs
> +    public static bool HasDotnetTestServerOption(CommandLineHandler commandLineHandler) =>
Extension method maybe?

2024-08-22 12:48 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/DotnetTest/DotnetTestHelper.cs
> +    private const string DotnetTestCliProtocol = "dotnettestcli";
I would keep this one in the Platform defaults constants. So we have everything in one place when we check what we expose.

2024-08-22 12:49 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs
> +            { HandshakeInfoPropertyNames.ExecutionId,  environment.GetEnvironmentVariable(EnvironmentVariableConstants.TESTINGPLATFORM_DOTNETTEST_EXECUTIONID) ?? string.Empty },
It cannot be empty or?  Is it a safenet?

2024-08-22 12:51 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/DotnetTest/DotnetTestConnection.cs
> +            executionId = Guid.NewGuid().ToString("N");
I don't see the check of current env var and the usage of this value.

2024-08-22 12:59 UTC, MarcoRossignoli requested changes
Discussed different refactoring offline

2024-08-23 13:47 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/CommandLine/InformativeCommandLineTestHost.cs
> +internal sealed class InformativeCommandLineTestHost(int returnValue, ServiceProvider serviceProvider) : ITestHost, IDisposable
`IServiceProvider`

2024-08-23 14:19 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/DotnetTest/IPC/Constants.cs
> +    internal const string DotnetTestCliProtocol = "dotnettestcli";
I'd like to have this one inside the platform command line so we have everything in the same place when we check what's we expose.

2024-08-23 14:20 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/DotnetTest/IPC/DotnetTestDataConsumer.cs
> +        if (DotnetTestConnection?.IsConnected == false)
I suppose we can also avoid to register  the `DotnetTestDataConsumer` is it's not connected so we save computation.

2024-08-23 14:22 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs
> +        string hostType = this switch
pls add a comment:

For now we don't inherit `TestHostOrchestratorHost` from the common one so we don't connect when we orchestrate.

2024-08-23 14:23 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
> +
remove line pls

2024-08-23 14:24 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
> +            serviceProvider.AddService(dotnetTestConnection);
I think we can always add it and retrive where is needed, we can check there `IsConnected` as condition to "do something or not" like register or not the custom `IDataConsumer`

2024-08-23 14:24 UTC, MarcoRossignoli requested changes
Some more cleanup/reorg but LGTM

2024-08-23 14:27 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
> +            serviceProvider.AddService(dotnetTestConnection);
Never mind me if you want to use `? GetService()` but I don't want to register the `IDataCollector` if we're not connected.

2024-08-23 14:29 UTC, MarcoRossignoli commented on src/Platform/Microsoft.Testing.Platform/DotnetTest/DotnetTestConnection.cs
> +        if (_dotnetTestPipeClient?.IsConnected == false)
it's not expected this call or? I prefer an opposite RoslynAssert  `_dotnetTestPipeClient?.IsConnected == true`

2024-08-26 08:18 UTC, MarcoRossignoli approved these changes

2024-08-26 09:18 UTC, merged